### ISSUE TITLE
App can't launch (dependency scanner)

### ISSUE THREAD

**Issue by Thoroughbreed** [peterhym21/H5.IntelliHouse2000App#5]
```IntelliHouse2000App.Helpers.DependencyInjectionScanner.HasAttribute[LifeTimeAttribute](Type type) in /Users/janandreasen/RiderProjects/MauiTestApp/H5.IntelliHouse2000App/IntelliHouse2000App/Helpers/DependencyInjectionScanner.cs:line 65
   at IntelliHouse2000App.Helpers.DependencyInjectionScanner.FindTypes(String namespace, ServiceLifetime defaultLifetime) in /Users/janandreasen/RiderProjects/MauiTestApp/H5.IntelliHouse2000App/IntelliHouse2000App/Helpers/DependencyInjectionScanner.cs:line 54
   at IntelliHouse2000App.Helpers.DependencyInjectionScanner.AddByNamespace(IServiceCollection services, String namespace, ServiceLifetime defaultLifetime) in /Users/janandreasen/RiderProjects/MauiTestApp/H5.IntelliHouse2000App/IntelliHouse2000App/Helpers/DependencyInjectionScanner.cs:line 23
   at IntelliHouse2000App.Helpers.DependencyInjectionScanner.RegisterDependencies(MauiAppBuilder builder) in /Users/janandreasen/RiderProjects/MauiTestApp/H5.IntelliHouse2000App/IntelliHouse2000App/Helpers/DependencyInjectionScanner.cs:line 11
   at IntelliHouse2000App.MauiProgram.CreateMauiApp() in /Users/janandreasen/RiderProjects/MauiTestApp/H5.IntelliHouse2000App/IntelliHouse2000App/MauiProgram.cs:line 18
   at IntelliHouse2000App.MainApplication.CreateMauiApp()```

**Comment by nicolaiheuck** [comment]
Fixed in #7
